#version 450

layout(set = 0, binding = 0) readonly buffer Input {
    int data[];
} in_buf;

layout(set = 0, binding = 1) buffer Output {
    int out_data[];
} out_buf;

layout(push_constant) uniform Constants {
    uint n;
    uint pad1;
    uint pad2;
    uint pad3;
} c;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    int all_true = 1;
    for (uint i = 0; i < c.n; i++) {
        if (in_buf.data[i] == 0) {
            all_true = 0;
            break;
        }
    }
    out_buf.out_data[0] = all_true;
}
