#!/usr/bin/env python3
"""Generate C stubs for the CPython symbols a side module imports.

Reads the side module's *own* import table rather than CPython headers, for a
reason that is the whole point of docs/WASM.md 7.5: there is no CPython built
for wasm32-unknown-emscripten on this machine, so there are no headers to take.
And guessing is not an option -- a WebAssembly import whose type does not match
the exporting module is a `LinkError` at instantiation time, before any code
runs, so an arity that is wrong by one produces "the module will not load"
rather than "the call misbehaves".

Usage:
    wasm-dis <side.wasm> -o side.wat
    python3 gen_pystubs.py side.wat > pystubs_gen.h
"""
import re
import sys

CMAP = {"i32": "int", "i64": "long long", "f32": "float", "f64": "double"}

# PyModuleDef_Init is not stubbed to 0 like the rest. In CPython it takes the
# static PyModuleDef and returns it as an object; PyO3's multi-phase `#[pymodule]`
# init is literally `return PyModuleDef_Init(&MODULE_DEF)`. Returning the
# argument unchanged is therefore the smallest thing that lets PyInit_* run to
# completion and hand back a pointer we can inspect -- which is what turns 7.5
# from "it loaded" into "it produced the right module definition".
SPECIAL = {"PyModuleDef_Init": "return a0;"}

FUNC_RE = re.compile(
    r'\(import "env" "(_?Py[A-Za-z0-9_]*)" \(func \$[\w$]+'
    r"((?: \(param [^)]*\))?)((?: \(result [^)]*\))?)\)\)"
)
DATA_RE = re.compile(r'\(import "GOT\.mem" "(_?Py[A-Za-z0-9_]*)"')
TYPE_RE = re.compile(r"i32|i64|f32|f64")


def main(path: str) -> None:
    wat = open(path).read()
    funcs = FUNC_RE.findall(wat)
    data = sorted(set(DATA_RE.findall(wat)))

    out = [
        "/* GENERATED by gen_pystubs.py from the side module's own import table.\n",
        " * Do not hand-edit. See docs/WASM.md 7.5 for why the types come from the\n",
        " * binary and not from CPython's headers. */\n\n",
        "static void stub_hit(const char *name);\n\n",
    ]
    for name, params, result in funcs:
        ptypes = TYPE_RE.findall(params) if params else []
        rt = TYPE_RE.findall(result)
        ret = CMAP[rt[0]] if rt else "void"
        args = ", ".join(f"{CMAP[t]} a{i}" for i, t in enumerate(ptypes)) or "void"
        tail = SPECIAL.get(name) or ("return 0;" if ret != "void" else "")
        out.append(f'{ret} {name}({args}) {{ stub_hit("{name}"); {tail} }}\n')

    out.append(
        "\n/* GOT.mem imports are *data*, not functions -- type objects and exception\n"
        " * singletons. Emscripten separates them from function imports because data\n"
        " * relocation is a different problem; wasip1 folded both into one flat list.\n"
        " * Sized generously; this probe never dereferences them. */\n"
    )
    for name in data:
        out.append(f"char {name}[512];\n")

    sys.stdout.write("".join(out))
    print(f"/* {len(funcs)} functions, {len(data)} data symbols */", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
